---
output:
  html_document:
    highlight: null
    css: style.css
    self_contained: no
    keep_md: true
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(stringr)

date <- "4/30/2020"

quarter <- "Spring2020"
date <- "04/30"
week_folder <- "04-30_Munro"


title <- "Human-in-the-Loop Machine Learning"


speaker <- "Robert Munro"
department <- ""
university <- ""
github_home <- "https://github.com/uchicago-computation-workshop"

#Update Weekly
issues_url <- "https://github.com/uchicago-computation-workshop/Spring2020/issues/2"
zoom_url <- "https://uchicago.zoom.us/meeting/register/tJIlc--gpzgtE9XfctGP_TeIVM5DFYcerXhE"


#Papers



#No Need to Edit
week_repo <- paste0("https://github.com/uchicago-computation-workshop/",quarter,"/tree/master/",week_folder)



```



<br>

<h3 class=pfblock-header> The Computational Social Science Workshop Presents </h3>

<h1 class=pfblock-header3> `r speaker`</h1>
<h3 class=pfblock-header3> `r department` </h3>
<h3 class=pfblock-header3> `r university` </h3>

<br><br>



<p class=pfblock-header3>The <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> at the University of Chicago cordially invites you to attend this week's talk:</p>



<br>

<div class=pfblock-header3>
<h2 class=pfblock-header>
  <a href=`r week_repo`> `r title` </a>
</h2>

<br>
</div>



<p class=footertext2>

**Summary:** More than 90% of machine learning applications improve with human feedback. For example, autonomous vehicles understand how to distinguish a "Pedestrian" from a "Cyclist" because people have spent 1000s of hours manually annotating pedestrians and cyclists in videos. However, when there are millions of hours of video from an autonomous vehicle, it might not be feasible to manually annotate more than 1% of that footage. If we just sample randomly, we will mostly get highway driving where the autonomous vehicle is already very skilled. So, we need to be smarter about how we sample. This talk is about "Active Learning" the process of deciding what raw data is the most optimal for human review. The general techniques for Active Learning apply to many machine learning problems in addition to autonomous vehicles, from commands spoken to smart devices to extracting information extraction from healthcare-related messages.


</p>

<br>

<h4 class=pfblock-header3> Thursday, `r date` </h4>
<h4 class=pfblock-header3> 11:00am-12:20pm </h4>

<br><br>

<p class=footertext2>

**`r speaker`** has worked as a leader at several Silicon Valley machine learning companies and also led AWS's first Natural Language Processing and Machine Translation solutions. Robert is the author of Human-in-the-Loop Machine Learning, covering practical methods for Active Learning, Transfer Learning, and Annotation. Robert organizes Bay Area NLP, the world's largest community of Language Technology professionals. Robert is also a disaster responder and is currently helping with the response to COVID-19.
 
</p>

<br>

<p class=footertext2>
**Registration**: The presentation will be held virtually on Zoom. For security purposes, please register through this [link](`r zoom_url`) to request access. Only accounts affiliated with the University of Chicago will be granted access.
</p>

This week's suggested readings:
<br>
<i>Human-in-the-Loop Machine Learning</i>   (manuscript available upon request):
<br>
Chapter 1: Introduction to Human-in-the-Loop Machine Learning
<br>
Chapter 4: Uncertainty Sampling
<br>
Chapter 5: Diversity Sampling 
<br>
Chapter 6: Advanced Active Learning 
<br>
If you are short on time, plese read two summary articles that Dr. Munro published recently on the PyTorch official blog:
<br>
[Active Learning with PyTorch](https://medium.com/pytorch/https-medium-com-robert-munro-active-learning-with-pytorch-2f3ee8ebec)
<br>
[Active Transfer Learning with PyTorch](https://medium.com/pytorch/active-transfer-learning-with-pytorch-71ed889f08c1)
<br><br>

---

<p class=footertext> The 2019-2020 <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> meets each Thursday from 11 a.m. to 12:20 p.m.. All interested faculty and graduate students are welcome.</p>



<p class=footertext>Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a comment on the <a href=`r issues_url`>issues page</a> of the <a href=`r week_repo`>workshop's public repository on GitHub.</a></p>
