---
output:
  html_document:
    highlight: null
    css: style.css
    self_contained: no
    keep_md: true
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(stringr)

date <- "5/07/2020"

quarter <- "Spring2020"
date <- "05/07"
week_folder <- "05-07_State"


title <- "The Structure of U.S. College Networks on Facebook"


speaker <- "Bogdan State"
department <- "Data Scientist"
university <- "Facebook"
github_home <- "https://github.com/uchicago-computation-workshop"

#Update Weekly
issues_url <- "https://github.com/uchicago-computation-workshop/Spring2020/issues/2"
zoom_url <- "https://uchicago.zoom.us/meeting/register/tJAvcu6vqzwvG9xbn1xIhFeLfieoHcpQS2Qc"


#Papers

week_paper_ref0 <- "Jan Overgoor, Bogdan State, and Lada A. Adamic 2020. 'The Structure of U.S. College Networks on Facebook'"
week_paper_file0 <- "scorecard_icwsm_final.pdf"



#No Need to Edit
week_repo <- paste0("https://github.com/uchicago-computation-workshop/",quarter,"/tree/master/",week_folder)

readings0 <- paste0("[", week_paper_ref0,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file0,")")



```



<br>

<h3 class=pfblock-header> The Computational Social Science Workshop Presents </h3>

<h1 class=pfblock-header3> `r speaker`</h1>
<h3 class=pfblock-header3> `r department` </h3>
<h3 class=pfblock-header3> `r university` </h3>

<br><br>



<p class=pfblock-header3>The <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> at the University of Chicago cordially invites you to attend this week's talk:</p>



<br>

<div class=pfblock-header3>
<h2 class=pfblock-header>
  <a href=`r week_repo`> `r title` </a>
</h2>

<br>
</div>



<p class=footertext2>

**Summary:** Anecdotally, social connections made in university have life-long impact. Yet knowledge of social networks formed in college remains episodic, due in large part to the difficulty and expense involved in collecting a suitable dataset for comprehensive analysis. To advance and systematize insight into college social networks, we describe a dataset of the largest online social network platform used by college students in the United States. We combine de-identified and aggregated
Facebook data with College Scorecard data, campus-level information provided by U.S. Department of Education, to produce a dataset covering the 2008-2015 entry year cohorts for 1,159 U.S. colleges and universities, spanning 7.6 million students. To perform the difficult task of comparing these networks of different sizes we develop a new methodology. We compute features over sampled ego-graphs, train binary classifiers for every pair of graphs, and operationalize distance between graphs as predictive accuracy. Social networks of different year cohorts at the same school are structurally more similar to one another than to cohorts at other schools. Networks from similar schools have similar structures, with the
public/private and graduation rate dimensions being the most distinguishable. We also relate school types to specific outcomes. For example, students at private schools have larger networks that are more clustered and with higher homophily
by year. Our findings may help illuminate the role that colleges play in shaping social networks which partly persist throughout people’s lives.


</p>

<br>

<h4 class=pfblock-header3> Thursday, `r date` </h4>
<h4 class=pfblock-header3> 11:00am-12:20pm </h4>

<br><br>

<p class=footertext2>

**`r speaker`** is a computational sociologist and a member of Facebook’s Core Data Science team. He received an M.A. and PhD in sociology from Stanford University. He is interested in using digital data to decipher the basic mechanisms of human social interaction. His experience includes over four years working as a data scientist in Silicon Valley. At Facebook, Bogdan’s contributions have ranged from developing large-scale business intelligence systems to improving the performance of ranking models. He gets excited easily when left near very large social datasets.
</p>

<br>

<p class=footertext2>
**Registration**: The presentation will be held virtually on Zoom. For security purposes, please register through this [link](`r zoom_url`) to request access. Only accounts affiliated with the University of Chicago will be granted access.
</p>

This week's suggested readings:

- `r readings0`


<br>

<br><br>

---

<p class=footertext> The 2019-2020 <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> meets each Thursday from 11 a.m. to 12:20 p.m.. All interested faculty and graduate students are welcome.</p>



<p class=footertext>Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a comment on the <a href=`r issues_url`>issues page</a> of the <a href=`r week_repo`>workshop's public repository on GitHub.</a></p>
