---
output:
  html_document:
    highlight: null
    css: style.css
    self_contained: no
    keep_md: true
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(stringr)

date <- "5/28/2020"

quarter <- "Spring2020"
date <- "05/28"
week_folder <- "05-28_Shaw"


title <- "Social Bootstraping of Economic Value"


speaker <- "Lynette Shaw"
department <- "Assistant Professor of Complex Systems <br>
Postdoctoral Scholar, Michigan Society of Fellows"
university <- "University of Michigan, Ann Arbor"
github_home <- "https://github.com/uchicago-computation-workshop"

#Update Weekly
issues_url <- "https://github.com/uchicago-computation-workshop/Spring2020/issues/6"
zoom_url <- "https://uchicago.zoom.us/meeting/register/tJIscuusqzwuE9DO7Oq3S1E9luJ7eYW4biK5"


#Papers

week_paper_ref0 <- "Lynette A. Shaw (2020) Something out of nothing: a Bayesian learning computational model for the social construction of value, The Journal of Mathematical Sociology, 44:2, 65-89."
week_paper_file0 <- "Shaw_2020_JMS.pdf"

week_paper_ref1 <- 'Lynette A. Shaw (2020) The inevitable sociality of money: the primacy of practical affirmation over conceptual consensus in the construction of bitcoin’s value, manuscript provded upon request.'


#No Need to Edit
week_repo <- paste0("https://github.com/uchicago-computation-workshop/",quarter,"/tree/master/",week_folder)

readings0 <- paste0("[", week_paper_ref0,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file0,")")



```



<br>

<h3 class=pfblock-header> The Computational Social Science Workshop Presents </h3>

<h1 class=pfblock-header3> `r speaker`</h1>
<h3 class=pfblock-header3> `r department` </h3>
<h3 class=pfblock-header3> `r university` </h3>

<br><br>



<p class=pfblock-header3>The <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> at the University of Chicago cordially invites you to attend this week's talk:</p>



<br>

<div class=pfblock-header3>
<h2 class=pfblock-header>
  <a href=`r week_repo`> `r title` </a>
</h2>

<br>
</div>



<p class=footertext2>

**Summary:** 
<br>

<u>Paper 1</u>
This article develops a formalism for the social construction of value. Using
a model based on Bayesian agents, it demonstrates how “something” arises
out of “nothing” via the emergence of durable value conventions and
shows how the developed framework can be used to investigate socially
constructed valuations under a variety of circumstances. The resulting
analysis clarifies why assumptions that collectives will converge upon the
“intrinsic” (i.e., non-socially originating) value of an object (e.g., market
efficiency) may not hold for mixed social and non-social valuation regimes,
explains the dependency of socially constructed valuations on early acci-
dents, demonstrates the effects of confident actors on constructed values,
and identifies the production of time-dependent ratcheting effects from the
interaction of bubbles with value conventions.
<br>
<u>Paper 2</u>
Bitcoin has gone from being the monetary project of a small online group to a globally exchanged money with a market valuation of several thousand dollars (USD) per unit. It has achieved this in spite of the irreconcilability between its material basis and the economic theories which inspired its creation. This article investigates how this was possible by applying a computationally grounded (Nelson 2017) approach to 100,000s of messages from Bitcoin’s two main online communities. Through this analysis, it identifies continuing divergence in participants’ understandings of why Bitcoin possesses value and an emergent focus on the social
problem of adoption. In demonstrating how this confrontation ultimately led to the promotion of activities that affirmed Bitcoin's value in practice, this article clarifies the primacy of shared meaning in the form of practical affirmations of worth, rather than conceptual understandings of its origins, in these communities’ “bootstrapping” of its initial economic value.

</p>

<br>

<h4 class=pfblock-header3> Thursday, `r date` </h4>
<h4 class=pfblock-header3> 11:00am-12:20pm </h4>

<br><br>

<p class=footertext2>

**`r speaker`**  received her Ph.D. in Sociology from the University of Washington in Summer 2016. Her dissertation research focused on social constructions of value in the rise of digital currencies such as Bitcoin and utilized a combination of agent-based modeling, automated analysis of text scraped from online communities and news, and quantitative analyses of metrics surrounding Bitcoin's price and investment trends. In addition to her continuing work on new digital currencies, she also has undertaken a series of projects related to modeling the emergence of cultural dynamics and shared social realities (i.e. social construction) out of the individual-level, cognitive processes responsible for automatic sense-making in situations (i.e. mental representation). 
</p>

<br>

<p class=footertext2>

**Registration**: The presentation will be held virtually on Zoom. For security purposes, please register through this [link](`r zoom_url`) to request access. Only accounts affiliated with the University of Chicago will be granted access.
</p>

<br>

This week's suggested readings:

- `r readings0`
- `r week_paper_ref1`


<br><br>

---

<p class=footertext> The 2019-2020 <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> meets each Thursday from 11 a.m. to 12:20 p.m.. All interested faculty and graduate students are welcome.</p>



<p class=footertext>Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a comment on the <a href=`r issues_url`>issues page</a> of the <a href=`r week_repo`>workshop's public repository on GitHub.</a></p>
